### ISSUE TITLE
Essential TODO list

### ISSUE THREAD

**Issue by Torrekie** [LNSSPsd/PhoenixBuilder#298]
- [x] Purge v8 engine (Completed in 4512a05 )
***
Added June 29th 23:
- [x] [Formalize expression](https://github.com/LNSSPsd/PhoenixBuilder/issues/301)
- [x] Combine `CommandSender` and `GameInterface`
- [x] Debug Mode is broken - Fix Debug Mode
***
Added July 6th:
- [ ] WebSocket API ~~_[See cc6e48c for more details]_~~
***
Added July 24th
Edited on November 12th
Marked as ***NOT PLANNED***
~~Combine `uqHolder` and `ResourcesControl`~~
***
Added Oct 11th:
- [ ] Remove zh localizations

**Comment by LNSSPsd** [comment]
>     * [ ]  iOS rootless support

Unfortunately darling might be essential, I built one w/ darling + Xcode toolchain and it works properly. Seems that Linux toolchain no longer works with iOS 15.

**Comment by Torrekie** [comment]
Maybe we can move all macOS/iOS build process to another CI that running macOS

**Comment by LNSSPsd** [comment]
> Replace V8 engine with more portable implementation (use system libnode or libv8, or remove this feature)

`go-v8` uses some v8 functions that no longer available in current builds, so using system one is not possible.

**Comment by Torrekie** [comment]
jya, let's remove go-v8 then

**Comment by CodePwn2021** [comment]
The use of websockets means that extensions related to PhoenixBuilder can be made in any programming language, so we need add supports for websocket.
A similar example is ``go-cqhttp``.
